/**
 * Aus 23 echten PDF-Präsentationen extrahiert (content/presentations/).
 * Zusammenfassungen/Fakten stammen ausschließlich aus den Dokumenten selbst,
 * ins Deutsche übertragen — keine Ergänzung aus Allgemeinwissen.
 * `dateKnown: false` heißt: kein Datum im Dokument gefunden, `date` ist der
 * Datei-Zeitstempel und dient nur der Sortierung, nicht als Aussage.
 */

// Auf reine Marken-Farben umgestellt (2026-08-14, gleicher Anlass wie
// CHANNEL_VAR in app.js: die --cat-*-Töne waren nie echte Sowespoke-Farben).
// Diese Map speist sowohl das Listen-Icon (.row__thumb, nur 3:1 nötig) als
// auch den Detail-Chip (Klartext-Badge, braucht volle 4.5:1) — deshalb
// durchgehend die dunkleren -text-Varianten, die für beide Kontexte sicher
// sind. Fällt "Sonstiges" bewusst nicht auf Grau/Schwarz zurück (Nutzer-
// Vorgabe: kein Weiß/Schwarz für diese Boxen).
const DOCTYPE_VAR = {
  "Beta-Feature": "--accent",
  "Feature-Guide": "--teal-text",
  "Strategie-Trend": "--turquoise-text",
  "Saisonal": "--accent",
  "Rechtliches": "--teal-text",
  "Sonstiges": "--turquoise-text",
};

const PRESENTATIONS = [
  {
    id: "product-roadmap-q3-2026",
    file: "Product Roadmap Q3 2026.pdf",
    title: "Product Roadmap Q3 2026: Microsoft-Advertising-Plattform-Fähigkeiten und Performance-Max-Neuerungen",
    // Titelfolie datiert nur auf das Quartal ("Q3, 2026"), kein exaktes
    // Erstellungsdatum im Dokument. Wie bei den anderen frisch hochgeladenen
    // Decks wird das Anzeige-/Sortierdatum auf den Upload-Tag gesetzt, damit
    // der Eintrag ganz oben erscheint — keine Aussage über ein echtes
    // Foliendatum.
    date: "2026-08-20", dateKnown: true,
    docType: "Beta-Feature",
    summaryDE: "Offizielle Microsoft-Advertising-Produkt-Roadmap für Q3 2026, gegliedert in zwei Teile: (01) Roadmap nach Plattform-Fähigkeit entlang sechs Investitionsbereichen — Show up in more places, Reach the right audiences, Maximize results with smarter bidding, Build performant creative, Transparent reporting & optimization, Simplify your workflows — sowie (02) Roadmap speziell nach Kampagnentyp für Performance Max. Jedes Feature ist mit Geo-Verfügbarkeit, unterstützten Kampagnentypen und Timeline (Closed/Open Pilot, GA-Datum oder bereits GA) versehen.",
    customerBlurb: "Microsoft hat die Produkt-Roadmap für Q3 2026 veröffentlicht — von neuen KI-Shopping-Erlebnissen (Brand Agents) über LinkedIn-Zielgruppen-Funktionen bis zu einem MCP-Server für KI-gestützte Kampagnenauswertung. Gerne gehen wir gemeinsam durch, welche der anstehenden Features für eure Konten und Timeline relevant sind.",
    keyFactsDE: [
      "Brand Agents: personalisierter KI-Shopping-Assistent, der Produkte in Microsoft Copilot und Bing auffindbar macht und Käufer:innen direkt auf der eigenen Website konvertiert; Geo: Global, Kampagnentyp: alle, aktuell Open Pilot, GA im August 2026.",
      "Bulk Company List Upload für LinkedIn-Profil-Targeting: bis zu 10.000 Firmennamen pro Kampagnen-Setup hochladen, Gebote auf Listenebene anpassen; Open Pilot, GA im September 2026 (zugrunde liegende Konsumentendaten schließen EWR-Länder aus).",
      "Cross-account Portfolio Bidding: Portfolio-Gebotsstrategien über mehrere Konten hinweg anwenden; GA mit einem Limit von 11.000 Kampagnen, im Pilotbetrieb bereits für bis zu 100.000 Kampagnen.",
      "Microsoft Advertising MCP Server: Kampagnenreports, Audits und Keyword-Recherche direkt aus KI-Assistenten wie M365 Copilot, Claude, ChatGPT oder Gemini heraus, in vier Schritten ohne Entwickler-Aufwand einzurichten; Open Pilot, global außer China und Indien.",
      "Verpflichtende Advertiser Identity Verification (AIV) für Australien und Vietnam: muss innerhalb von 30 Tagen nach Anmeldung abgeschlossen werden, damit Anzeigen ab dem 1. Juli 2026 ohne Unterbrechung weiterlaufen; Status GA.",
    ],
    emailHookDE: null,
    pageCount: 19,
  },
  {
    id: "holiday-insights-2026-core-de",
    file: "2026 Core Holiday Insights – DE – Jun2026.pdf",
    title: "Retail Peak 2026 (Deutschland): Wirtschaftsausblick, KI in der Suche und Performance-Max-Empfehlungen",
    // Datenperioden im Dokument (u. a. "Mar 2026", "Apr 2026", Prognose
    // Okt.–Dez. 2026) legen Juni 2026 als Erstellungszeitraum nahe, ein
    // explizites Datum steht auf keiner Folie. Auf ausdrücklichen Wunsch
    // von Angelika (11.08.2026) wird das Anzeige-/Sortierdatum zusätzlich
    // auf den Upload-Tag gesetzt, damit der Eintrag ganz oben mit
    // "Neu"-Badge erscheint — keine Aussage über das echte Foliendatum.
    date: "2026-08-08", dateKnown: true,
    docType: "Saisonal",
    summaryDE: "Umfassende Holiday-2026-Strategiepräsentation für den deutschen Markt (Teil einer EU6-Reihe) mit sechs Themenblöcken: makroökonomischer Ausblick (Inflation, Verbrauchervertrauen, Auswirkungen des Iran-Konflikts auf die Energiekosten), struktureller Wandel hin zu KI-gestützter Suche, Markt-Performance rund um Black Friday, der Wert von Markenbekanntheit, Nachfrage-/Klick-Prognosen für Okt.–Dez. 2026 sowie Empfehlungen zu Performance Max und Audience Ads.",
    customerBlurb: "Microsoft hat eine umfassende Analyse zur Feiertagssaison 2026 in Deutschland veröffentlicht — von der Wirtschaftslage über den KI-Wandel in der Suche bis zu konkreten Kampagnenempfehlungen für Performance Max und Audience Ads. Gerne gehen wir mit euch durch, welche der Handlungsempfehlungen für eure Kampagnenplanung ab Herbst relevant sind.",
    keyFactsDE: [
      "Alle sechs großen EU-Märkte liegen laut Deck über dem EZB-Inflationsziel von 1,0 %; Spanien (3,4 %) und UK (3,1 %) am weitesten vom Zielwert entfernt (Stand März 2026).",
      "Eine anhaltende Sperrung der Straße von Hormuz gilt laut Deck als größter Unsicherheitsfaktor für die Kostenentwicklung im Peak 2026, mit Auswirkungen auf Kraftstoff-, Fracht- und Verpackungskosten in Q3/Q4.",
      "KI-Shopping-Tool-Nutzung in Deutschland liegt laut zitierter McKinsey-Studie bei 66 % (Q1 2026); Bing-Nutzer:innen setzen KI-Tools laut Deck 10 % häufiger ein als Google-Nutzer:innen.",
      "Black-Friday-Woche treibt laut internen Microsoft-Daten das höchste Klickvolumen, doch die Nachfrage baut sich bereits ab Oktober stetig auf; für Deutschland wird ein Rückgang der Conversion-Kosten (CPA) von rund 20 % vor Black Friday berichtet.",
      "Prognose für Deutschland (Okt.–Dez. 2026): Klicks +5 % YoY, Suchanfragen -5 % YoY; stärkstes Klickwachstum bei Computer & Unterhaltungselektronik (+9 %) und Haus & Garten (+8 %).",
    ],
    emailHookDE: null,
    pageCount: 60,
  },
  {
    id: "holiday-insights-2026-display-video-de",
    file: "2026 Display & Video Holiday Insights – DE – Jun2026.pdf",
    title: "Display & Video Retail Insights (Deutschland, Juni 2026): Die Customer Journey ist nicht linear",
    // Titelfolie nennt explizit "Germany - June 2026". Auf ausdrücklichen
    // Wunsch von Angelika (11.08.2026) wird das Anzeige-/Sortierdatum
    // zusätzlich auf den Upload-Tag gesetzt, damit der Eintrag ganz oben
    // mit "Neu"-Badge erscheint — keine Aussage über das echte Foliendatum.
    date: "2026-08-07", dateKnown: true,
    docType: "Saisonal",
    summaryDE: "Präsentation des Microsoft-Teams 'Global Measurement & Insights' (Deutschland, Juni 2026) zu Display & Video im Einzelhandel: Wirtschaftsausblick, Profil der High-Intent-Shopper:innen bei Microsoft-Medien, die Consumer Decision Journey vor/während/nach dem Kauf, ein Markov-Attributionsmodell zum letzten Holiday-Peak sowie Content-Konsum-Insights auf MSN.",
    customerBlurb: "Microsoft zeigt in einer aktuellen Analyse (Juni 2026), dass Display & Video laut Multi-Touch-Attribution für 15 % aller Conversions verantwortlich sind — mehr als doppelt so viel wie eine reine Last-Click-Betrachtung zeigt. Für Kampagnen, die aktuell nur auf Search setzen, lohnt sich daher ein Blick auf ergänzende Display-/Video-Formate.",
    keyFactsDE: [
      "Bei Multi-Touch-Attribution (statt Last-Click) tragen Display/Native/Video laut Deck 15 % statt 6 % zu Conversions bei — ein 2,3-facher Einfluss gegenüber der reinen Last-Click-Betrachtung.",
      "Deutsche Internetnutzer:innen kaufen laut Global-Web-Index-Daten 1,5x wahrscheinlicher online als der durchschnittliche Internetnutzer; 62 % der Microsoft-Media-Nutzer:innen gehen mit der Absicht online, vor dem Kauf zu vergleichen ('Browse-to-buy').",
      "Für 18 % der Nutzer:innen sind Microsoft-Media-Eigenschaften (MSN, Bing, Outlook.com u. a.) der letzte Touchpoint vor dem Besuch einer Retail-Marken-Website (Microsoft interne Daten, Deutschland).",
      "Die Customer Journey endet laut Deck nicht mit dem Kauf: Kategorie-Entdeckung und Marken-/Produktbewertung erreichen danach sogar ein höheres Intent-Niveau als davor.",
      "Shopping-Engagement auf MSN ist laut Deck werktags am Vormittag am höchsten, nicht an Wochenenden oder zu isolierten 'Shopping-Momenten'.",
    ],
    emailHookDE: null,
    pageCount: 25,
  },
  {
    id: "holiday-insights-2026-two-pager-de",
    file: "2026 Holiday Insights Two Pager – DE – Jun2026.pdf",
    title: "Trends im Weihnachtshandel Deutschland 2026 (Two-Pager, DE/EN)",
    // Kein explizites Monatsdatum im Dokument (nur "Deutschland, 2026"),
    // Juni 2026 aus derselben Upload-Charge wie die anderen "Jun2026"-Decks
    // übernommen. Auf ausdrücklichen Wunsch von Angelika (11.08.2026) wird
    // das Anzeige-/Sortierdatum zusätzlich auf den Upload-Tag gesetzt,
    // damit der Eintrag ganz oben mit "Neu"-Badge erscheint — keine
    // Aussage über das echte Foliendatum.
    date: "2026-08-06", dateKnown: true,
    docType: "Saisonal",
    summaryDE: "Zweiseitige, zweisprachige (DE/EN) Kompakt-Übersicht zu Weihnachtshandel-Trends in Deutschland 2026: Verbraucherausgaben nach Einkaufskanal, wichtigste Kaufentscheidungsfaktoren, Conversion-/CPA-Veränderungen nach Kategorie sowie ein rollierender Suchindex mit Geräte-, Kategorie- und Keyword-Aufschlüsselung für Juli–Dezember 2025.",
    customerBlurb: "Diese kompakte Zwei-Seiten-Übersicht von Microsoft fasst die wichtigsten Trends für den deutschen Weihnachtshandel 2026 zusammen — inklusive konkreter Conversion-/CPA-Veränderungen je Kategorie und Empfehlungen zu Performance Max, Dynamic Search Ads und Zielgruppensignalen für nachhaltige Geschenke.",
    keyFactsDE: [
      "64 % nutzen laut Shopify-Quelle (2025) KI-Tools für Weihnachtseinkäufe, bei den 18- bis 24-Jährigen sogar 84 %.",
      "36 % der deutschen Verbraucher:innen bevorzugen laut Mintel (2025) nachhaltige Geschenke — empfohlen werden dafür In-Market-, Similar- und Predictive-Targeting-Audiences.",
      "Stärkstes Conversion-Wachstum Q4 2025 laut Deck: Bekleidung & Accessoires (+106 %, CPA -42 %), Haustierbedarf (+93 %, CPA -43 %), Spielzeug & Hobby (+62 %, CPA -21 %).",
      "Black Friday und Cyber Monday gelten laut Mintel (2025) als 'neuer Auftakt' der mehrwöchigen deutschen Weihnachtssaison — empfohlen werden durchgängige statt eintägige Kampagnen.",
      "Desktop erzielt bei der Produktrecherche eine rund 1,8x höhere Klickrate als Mobil (Microsoft interne Daten, 2025) — bei Wohnmöbeln liegt der Abstand sogar bei 4,5x.",
    ],
    emailHookDE: null,
    pageCount: 4,
  },
  {
    id: "holiday-insights-2026-mobile-tech-telco-de",
    file: "2026 Mobile Tech Telco Holiday Insights One Pager - DE - Aug2026.pdf",
    title: "Feiertagsinsights im Mobilfunk (Deutschland 2026): Refurbished, KI und frühe Reichweite",
    date: "2026-08-01", dateKnown: true,
    docType: "Saisonal",
    summaryDE: "Einseitiger, zweisprachiger (DE/EN) Insights-Bogen zu Feiertagstrends im Mobilfunk-/Tech-Segment für Deutschland 2026: Trends zu Refurbished-Smartphones, früher Werbereichweite und KI als Einkaufshelfer, ergänzt um Marken-Rankings nach Suchanfragen sowie eine Such-/Klick-/CPC-Prognose für Mobiltelefone & Zubehör (Aug.–Dez. 2024–2026).",
    customerBlurb: "Microsoft hat aktuelle Feiertags-Insights für den Mobilfunk-/Tech-Bereich veröffentlicht: 55 % der EU-Verbraucher:innen erwägen den Kauf eines refurbished Smartphones, und die Teilnahme an Black Friday/Cyber Monday ist 2025 in Deutschland weiter gestiegen. Für Mobilfunk- und Elektronik-Kund:innen lohnt sich ein Blick auf die empfohlene frühe Kampagnenausrichtung im November.",
    keyFactsDE: [
      "Teilnahme an Black Friday stieg 2025 in Deutschland laut YouGov auf 38 %, an Cyber Monday auf 24 %.",
      "55 % der EU-Verbraucher:innen beabsichtigen laut Recommerce (2026), ein refurbished Smartphone zu kaufen — Preis ist dabei der wichtigste Kaufgrund; empfohlen werden Shopping-Kampagnen mit Preiserweiterungen.",
      "66 % der deutschen Verbraucher:innen nutzen laut McKinsey (2026) KI beim Einkaufen zur Produktrecherche, zum Vergleich und zur Kaufplanung.",
      "iPhone dominiert laut internen Microsoft-Suchdaten (2025) die Suchanfragen bei Mobiltelefonen; die wachstumsstärksten Marken Nov./Dez. gegenüber Sept./Okt. waren jedoch OnePlus (+34 %), Motorola (+23 %) und Aldi Talk (+15 %).",
      "48 % der Käufer:innen entdecken große Verkaufsaktionen laut YouGov über Online-Werbung — empfohlen wird der frühe Einsatz von Zielgruppenanzeigen zu Monatsbeginn.",
    ],
    emailHookDE: null,
    pageCount: 2,
  },
  {
    id: "ai-optimization-search",
    file: "AI Optimization for Search (1).pdf",
    title: "KI-Optimierung für die Suche (AI Optimization)",
    date: "2026-03-02", dateKnown: true,
    docType: "Beta-Feature",
    summaryDE: "Die Präsentation stellt \"AI optimization\" vor, ein optionales neues Toggle für Search-Kampagnen, das mithilfe von Microsoft-KI die Suchbegriffsabdeckung erweitert, Anzeigentexte dynamisch personalisiert und Ziel-URLs intelligent optimiert. Ein geschlossener Pilot startet laut Dokument am 2. März 2026, unterstützt durch MAP, API und Google Import. Das Dokument vergleicht die Funktion ausführlich mit Googles \"AI Max\" und beantwortet in einem FAQ- und Anhang-Teil typische Fragen zu Funktionsumfang, Gebotsstrategien, Copilot-Auswirkungen und Teilnahmebedingungen.",
    customerBlurb: "Microsoft testet aktuell eine neue KI-Funktion für Search-Kampagnen, die automatisch mehr passende Suchbegriffe abdeckt, Anzeigentexte anpasst und Ziel-Seiten optimiert. Der Pilot ist aktuell geschlossen, könnte aber für eure Kampagnen mit stabilem Conversion-Tracking interessant sein.",
    keyFactsDE: [
      "Kernfunktionen: KI-gestütztes Suchbegriff-Matching, dynamische Text-Customization und Final-URL-Expansion.",
      "Geschlossener Pilot ab 2. März 2026; unterstützt MAP, API und Google Import.",
      "Nur konversionsbasierte Gebotsstrategien (Maximize Conversions/Ziel-CPA, Maximize Conversion Value/Ziel-ROAS) — kein Enhanced CPC, manuelles Bieten oder Portfolio-Strategien.",
      "Teilnahme: aktive Search-Kampagnen, verifiziertes Tracking mit über 30 Conversions/Monat, Broad Match/DSA/automatisiertes Bieten, kein Performance Max.",
      "Keine garantierte Auswirkung auf Copilot-Sichtbarkeit; bestehende Negative Keywords bleiben erhalten.",
    ],
    emailHookDE: "Für Kund:innen mit stabilem Conversion-Tracking können wir ab dem 2. März 2026 die Teilnahme am geschlossenen Pilotprogramm für KI-Optimierung in Search-Kampagnen anfragen, das Suchbegriffs-Reichweite, Anzeigentexte und Ziel-Seiten automatisiert per KI verbessert.",
    pageCount: 26,
  },
  {
    id: "conversion-mastery",
    file: "Conversion mastery_Tracking, goals & Performance Max essentials (Presentation).pdf",
    title: "Conversion Mastery: Tracking, Ziele und Performance-Max-Grundlagen",
    date: "2026-02-24", dateKnown: true,
    docType: "Feature-Guide",
    summaryDE: "Schulungswebinar von Microsoft Advertising mit drei Themenblöcken: Universal Event Tracking (UET), zielgerichtete Conversion-Goals inklusive Offline- und API-Conversions sowie automatisierte Gebotsstrategien, und Grundlagen zu Performance Max. Reine Erklärung bestehender Funktionen, keine Ankündigung neuer Features.",
    customerBlurb: "Microsoft hat kürzlich ein Schulungswebinar zu den Grundlagen von Tracking, Conversion-Zielen und Performance Max veröffentlicht. Falls es bei euch Fragen zum Tracking-Setup gibt, fassen wir die wichtigsten Punkte gerne für euch zusammen.",
    keyFactsDE: [
      "UET-Tag als Grundlage für Tracking, Remarketing und automatisiertes Bieten; empfohlen: sitewide JavaScript-Tagging ohne iFrames.",
      "Consent Mode für UET (ad_storage) ist im EWR, UK und der Schweiz standardmäßig auf 'denied' gesetzt.",
      "Offline-Conversion-Import braucht Microsoft Click ID, Conversion-Name, Zeitpunkt; Obergrenze 100.000 Zeilen/200 MB pro Upload, bis 90 Tage rückwirkend.",
      "Conversions-API (Server-to-Server) laut Folie mit Pilotstart Mai 2025, braucht Freigabeprozess und Entwicklungsaufwand.",
      "Performance Max: KI-gesteuert über alle Placements, kein Video-Asset zwingend, LinkedIn-Targeting als Signal nutzbar, Ausspielung auch in Copilot möglich.",
    ],
    emailHookDE: null,
    pageCount: 56,
  },
  {
    id: "data-driven-attribution",
    file: "Data Driven Attribution - Feature guide.pptx.pdf",
    title: "Datengetriebene Attribution (Data-Driven Attribution) – Feature-Guide",
    date: "2026-04-02", dateKnown: false,
    docType: "Beta-Feature",
    summaryDE: "Der Guide erklärt das Data-Driven-Attribution-Modell (DDA), das per maschinellem Lernen jedem Werbekontakt entlang des Conversion-Pfads einen anteiligen Beitrag zuweist, statt wie beim Last-Click-Modell alles dem letzten Klick zuzuschreiben. Beschrieben werden der Model-Comparison-Report und die manuelle Rückwechsel-Option; ein FAQ-Abschnitt behandelt die Pilotphase, in der sich Attributionsgewichte über Wochen stabilisieren.",
    customerBlurb: "Microsoft Advertising bietet jetzt ein datengetriebenes Attributionsmodell an, das jedem Werbekontakt entlang der Kaufentscheidung einen realistischen Anteil am Erfolg zuschreibt, statt alles dem letzten Klick gutzuschreiben. Für eure Kampagnen könnte das genauere Einblicke liefern, welche Anzeigen wirklich wirken.",
    keyFactsDE: [
      "DDA verteilt Conversion-Credit anteilig auf alle Touchpoints statt alles dem letzten Klick zuzuschreiben.",
      "Model Comparison Report (Reports > Performance > Conversion Model Compare) zeigt die Lift zwischen DDA und Last-Click.",
      "Für Nicht-tROAS-Strategien fällt der Conversion-Credit auf Last-Click zurück.",
      "Volle Stabilisierung dauert mehrere Wochen; größere Ziel-/Budgetänderungen währenddessen nicht empfohlen.",
      "Rückwechsel zu Last-Click manuell über die Conversion-Ziel-Einstellungen möglich.",
    ],
    emailHookDE: "Mit dem neuen datengetriebenen Attributionsmodell erkennen Kund:innen erstmals, welchen tatsächlichen Beitrag jede einzelne Anzeige entlang der Customer Journey zum Kaufabschluss leistet – für präzisere Budgetentscheidungen.",
    pageCount: 8,
  },
  {
    id: "partner-pulse-feb-2026",
    file: "February 2026 Partner Pulse Deck.pdf",
    title: "Microsoft Advertising Partner Pulse – Februar 2026",
    date: "2026-02-18", dateKnown: true,
    docType: "Sonstiges",
    summaryDE: "Monatliches Partner-Update mit: Neuigkeiten zum Partnerprogramm (neues Partner-Portal, Pflicht-Reauthentifizierung, Partner-Celebration-Awards März/April 2026), einer Konsumentenstudie zur Fußball-WM, einem Partner-Spotlight (Agentur WORX) und einem Überblick zu neuen KI-/Copilot-Funktionen.",
    customerBlurb: "Aus dem aktuellen Microsoft-Partner-Update: Es gibt eine neue, öffentlich zugängliche Vorschau eines KI-Performance-Dashboards in den Bing Webmaster Tools, das zeigt, wie oft eure Website in KI-generierten Antworten zitiert wird. Auf Wunsch schauen wir uns das gerne gemeinsam für eure Domain an.",
    keyFactsDE: [
      "Konsumentenstudie: rund 70 % (US) bzw. 62 % (UK) der Fans planen Reisen zum Turnier; ~62 % (US) bzw. 49 % (UK) wollen eine Watch Party ausrichten.",
      "Partner-Spotlight WORX: laut eigenen Zahlen 43 % mehr Lead-Volumen, 77 % geringere Neukunden-CPA, 420 % mehr qualifizierte Leads.",
      "Copilot-App-Nutzung wuchs laut Sensor-Tower-Daten (Jan–Aug 2025) wöchentlich um +91 % — stärkstes Wachstum unter verglichenen KI-Assistenten.",
      "Neue KI-Performance-Auswertung in Bing Webmaster Tools als 'Public Preview': zeigt Zitationen und Sichtbarkeit in KI-Antworten.",
      "Neuer Performance-Max-Lernpfad mit Kurs und Badge in der Learning Lab; Partner-Workshop zu Copilot am 4. März 2026.",
    ],
    emailHookDE: "Website-Betreiber:innen können ab sofort in der öffentlichen Vorschau des neuen KI-Performance-Dashboards in Bing Webmaster Tools einsehen, wie oft und wo ihre Seiten in KI-generierten Antworten zitiert werden.",
    pageCount: 50,
  },
  {
    id: "three-eras-of-the-web",
    file: "How to navigate and win across the three eras of the web (Presentation).pdf",
    title: "Performen und transformieren: Gewinnen in den drei Epochen des Webs",
    date: "2026-05-28", dateKnown: true,
    docType: "Strategie-Trend",
    summaryDE: "Thought-Leadership-Präsentation darüber, wie KI das Kaufverhalten vom klassischen Klicken hin zu autonomem Handeln verändert: 'Human Web', 'LLM Web' und 'Agentic Web' — für jede Epoche werden passende Microsoft-Advertising-Werkzeuge vorgestellt (AI Max, Audience Generation, Microsoft Grounding/GEO, Brand Agents, Copilot Checkout).",
    customerBlurb: "Microsoft hat vorgestellt, wie Copilot Checkout mittlerweile den Kaufabschluss direkt im Gespräch ermöglicht, bei bereits über einer halben Million angebundener Händler. Das könnte relevant werden, sobald eure Zielgruppe verstärkt über KI-Assistenten einkauft.",
    keyFactsDE: [
      "Laut zitierter Studie nutzen 41 % der Verbraucher:innen KI-Assistenten zur Produktrecherche, ein Drittel zur Bewertungs-Interpretation, 31 % zur Schnäppchensuche.",
      "AI Max für Search erzielte laut Folie +5 % höhere CTR bei KI-optimierten Anzeigentexten.",
      "'Audience Generation' erlaubt Zielgruppenbeschreibung in natürlicher Sprache statt manueller Konfiguration.",
      "'KI-Sichtbarkeit in Microsoft Clarity' als 'Coming Soon' angekündigt.",
      "Copilot Checkout: Kaufabschluss direkt im Gespräch, über eine halbe Million angebundene Händler.",
    ],
    emailHookDE: "Mit Copilot Checkout können Kund:innen ihren Einkauf jetzt direkt im Copilot-Gespräch abschließen, ohne die Unterhaltung zu verlassen – bereits bei über einer halben Million angebundener Händler verfügbar.",
    pageCount: 62,
  },
  {
    id: "lift-measurement",
    file: "Lift measurement - Feature Guide_Nov GA (1).pdf",
    title: "Lift Measurement – Wirkungsmessung für Audience Ads",
    date: "2026-08-02", dateKnown: false,
    docType: "Feature-Guide",
    summaryDE: "Feature-Guide zu 'Lift measurement' für Audience Ads: erklärt, wie sich mit Search-, Visit- und Conversion-Lift-Studien direkt in der Plattform messen lässt, ob Nutzer:innen nach Kontakt mit Audience-Anzeigen eher suchen, besuchen oder konvertieren, inkl. Schritt-für-Schritt-Anleitung.",
    customerBlurb: "Mit Lift-Measurement-Studien lässt sich direkt in Microsoft Advertising messen, ob eure Audience-Anzeigen tatsächlich mehr Suchen, Website-Besuche und Käufe auslösen. Das wäre eine gute Möglichkeit, die Wirkung eurer Kampagnen konkret zu belegen.",
    keyFactsDE: [
      "Nutzer:innen sind nach Audience-Ad-Kontakt im Schnitt 3x wahrscheinlicher zu suchen, 4x die Website zu besuchen, 6x zu konvertieren (Microsoft-Daten Jan–März 2024).",
      "Verfügbarkeit laut Statustabelle: aktuell interne Nutzer, laut Fußnote grundsätzlich verfügbar, noch in Experimentierphase.",
      "Voraussetzungen: laufende Audience-Kampagnen, mind. 1 Mio. Impressions (nur PC), UET-Tag für Visit-/Conversion-Lift.",
      "Analysezeitraum: 3 Wochen Experiment plus 1 Woche Auswertung.",
      "Empfehlung: pro Kunde nur eine Studie gleichzeitig, da kostenintensiv und kapazitätsbeschränkt.",
    ],
    emailHookDE: "Mit Lift-Measurement-Studien lässt sich für Kund:innen konkret nachweisen, wie stark ihre Audience-Kampagnen echte Nutzer:innen zum Suchen, Besuchen und Kaufen bewegen.",
    pageCount: 17,
  },
  {
    id: "msa-mcp-open-beta",
    file: "MSA API MCP Server - Open Beta Pilot Pitch Deck (1).pdf",
    title: "Microsoft Advertising API MCP Server: Offene Beta",
    date: "2026-08-02", dateKnown: false,
    docType: "Beta-Feature",
    summaryDE: "Der Microsoft Advertising API MCP Server ist jetzt in offener Beta verfügbar. Er verbindet KI-Assistenten (Microsoft 365 Copilot, Claude, ChatGPT, Gemini) über das MCP-Protokoll direkt mit dem Advertising-Konto für Abfragen in natürlicher Sprache. In der offenen Beta nur lesender Zugriff, keine Kampagnenänderungen.",
    customerBlurb: "Microsoft Advertising lässt sich jetzt in der offenen Beta direkt mit KI-Assistenten wie Copilot oder Claude verbinden — Kampagnenberichte und Auswertungen lassen sich damit einfach per Texteingabe abrufen. Bisher nur lesend, aber ein spannender erster Schritt.",
    keyFactsDE: [
      "Offene Beta, reiner Lesezugriff — Kampagnenänderungen noch nicht möglich.",
      "Kompatibel mit Microsoft 365 Copilot, Claude, ChatGPT, Gemini und weiteren MCP-fähigen Assistenten.",
      "Referenzpartner laut Deck: Stagwell Media Platform, ClickTech, Mediaplus, Optmyzr, realtor.com, Groupon u. a.",
      "Zitat Dan Roberts (Stagwell): Kampagnen-Audit-Zeiten von Stunden auf Minuten reduziert.",
      "Einrichtung in vier Schritten: Assistent wählen, Azure-AD-App registrieren, MCP-Server verbinden, verifizieren.",
    ],
    emailHookDE: "Kunden können ab sofort ihre gewohnten KI-Assistenten (z. B. Copilot oder Claude) direkt mit Microsoft Advertising verbinden und Kampagnenberichte oder Keyword-Recherchen per Texteingabe abrufen, statt manuell im Interface zu suchen.",
    pageCount: 8,
  },
  {
    id: "mcp-use-cases",
    file: "Microsoft Advertising MCP Server - Use Cases.pdf",
    title: "Microsoft Advertising MCP Server: Anwendungsfälle",
    date: "2026-08-02", dateKnown: false,
    docType: "Feature-Guide",
    summaryDE: "Sammlung konkreter Anwendungsfälle für den Microsoft Advertising MCP Server: Reporting & Kampagnen-Insights (Account-Zusammenfassungen, Deep-Dives, Ad-/Keyword-Performance, Audience Insights, Anomalie-Alerts) sowie Cross-Platform-Vergleiche zwischen Google und Microsoft (Struktur, Einstellungen, Performance, Keywords, Asset-Gruppen, Zielgruppen) — jeweils per Frage in natürlicher Sprache statt manuellem Report-Bau.",
    customerBlurb: "Ergänzend zur MCP-Server-Beta hat Microsoft eine Sammlung konkreter Anwendungsfälle veröffentlicht — von schnellen Kampagnen-Zusammenfassungen bis zum Plattformvergleich mit Google Ads. Gerne zeigen wir euch anhand eures Kontos, was davon für euch praktisch nutzbar wäre.",
    keyFactsDE: [
      "Leadership-taugliche Ausgaben in mehreren Formaten: Excel-Tabelle, Power-BI-Datensatz, Folien-Bullet-Points, Fließtext-Zusammenfassung.",
      "Anomalie- und Schwellenwert-Alerts erkennen Spend-Spitzen, Conversion-Einbrüche oder CTR-Einbrüche automatisch.",
      "Cross-Platform-Vergleich erfordert zusätzlich eine Google-Ads-MCP-Integration.",
      "Entity-Lookups liefern gefilterte Listen (z. B. alle aktiven PMax-Kampagnen) ohne Report-Erstellung.",
      "Jedes Beispiel ist laut Dokument nur ein Ausgangspunkt — Fragen lassen sich frei formulieren.",
    ],
    emailHookDE: null,
    pageCount: 4,
  },
  {
    id: "new-year-new-budgets",
    file: "New Year, New Budgets with Microsoft Ads (Presentation) (1).pdf",
    title: "Neues Jahr, neue Budgets: Microsoft Ads Webinar zu KI-Trends 2026",
    date: "2026-01-27", dateKnown: true,
    docType: "Strategie-Trend",
    summaryDE: "Webinar-Mitschrift vom 27.01.2026 zu Trends bei Microsoft Ads und KI: wachsende Rolle von Copilot im Microsoft-Ökosystem, Verschiebung des Suchverhaltens zugunsten von Bing, sowie Optimierungshinweise für Performance Max und Audience Ads.",
    customerBlurb: "Aus dem Jahresstart-Webinar von Microsoft: Copilot wird als Werbefläche immer relevanter, und Audience Ads lassen sich jetzt sogar gezielt auf beliebte Gaming-Titel wie Candy Crush ausspielen. Falls eure Zielgruppe dort aktiv ist, könnte das eine neue Reichweitenquelle sein.",
    keyFactsDE: [
      "Copilot-App-Sitzungen stiegen Jan–Aug 2025 um +91 % (wöchentlich) — stärker als Perplexity, Gemini, Claude, ChatGPT, Grok.",
      "Anzeigen in Copilot steigern die CTR laut Microsoft-1P-Daten branchenübergreifend im Schnitt um +153 %.",
      "Bing gewinnt Marktanteile: +2,1 Punkte USA (PC), +3,4 Punkte weltweit (PC), Feb. 2023 bis Juni 2025.",
      "Performance Max: durchschnittlich 3x ROAS-Steigerung und -32 % CPA gegenüber reiner Search-Werbung.",
      "Neu: Audience Ads gezielt auf King-Gaming-Titel wie Candy Crush, inkl. neuem Rewarded-Vertical-Video-Format.",
    ],
    emailHookDE: "Werbetreibende können ihre Audience Ads jetzt gezielt auf beliebte King-Gaming-Titel wie Candy Crush platzieren und dort mit dem neuen Rewarded-Vertical-Video-Format zusätzliche Reichweite erschließen.",
    pageCount: 44,
  },
  {
    id: "conversions-retract-restate",
    file: "Online conversions update—retract and restate.pdf",
    title: "Online-Conversions nachträglich korrigieren: Retract & Restate",
    date: "2026-08-02", dateKnown: false,
    docType: "Beta-Feature",
    summaryDE: "Pilot-Feature-Guide zu einer neuen Möglichkeit, bereits erfasste Online-Conversions nachträglich zu korrigieren: 'Restate' passt den Conversion-Wert an, 'Retract' entfernt die Conversion komplett — nützlich bei Retouren, Stornos oder Eingabefehlern. Voraussetzung: transaction_id über UET-Custom-Event.",
    customerBlurb: "Microsoft Advertising erlaubt jetzt, bereits erfasste Conversions nachträglich zu korrigieren oder zu entfernen — praktisch bei Retouren, Stornos oder Eingabefehlern. Das sorgt dafür, dass eure Reporting-Zahlen auch im Nachhinein stimmen.",
    keyFactsDE: [
      "Restate ändert nur den Conversion-Wert, nicht die Conversion-Anzahl.",
      "Retract setzt den Wert auf 0,00 und zieht den Betrag vom Gesamtumsatz ab.",
      "Verfügbar für Online- und Offline-Conversions, erfordert zwingend eine transaction_id.",
      "Upload über Excel/CSV-Template mit Transaction ID, Conversion Name, Adjustment Time/Type/Value.",
      "Anpassungen werden nicht in Hotel-Ads-Berichten berücksichtigt.",
    ],
    emailHookDE: "Kunden können künftig fehlerhafte oder durch Retouren/Stornos veränderte Conversion-Werte im Nachhinein korrigieren, statt mit dauerhaft verzerrten Reporting-Zahlen zu arbeiten.",
    pageCount: 8,
  },
  {
    id: "optimization-experiments",
    file: "Optimization Experiments Feature Guide.pdf",
    title: "Optimization Experiments: A/B-Tests jetzt auch für Shopping, Audience und Performance Max",
    date: "2026-04-23", dateKnown: false,
    docType: "Beta-Feature",
    summaryDE: "Optimization Experiments erlauben kontrollierte A/B-Tests einzelner Kampagnenänderungen mit statistisch belastbaren Ergebnissen. Neu: jetzt auch für Shopping-, Audience- und Performance-Max-Kampagnen (bisher nur Search), mit neuer einheitlicher Ergebnisseite. Status laut Guide: Closed Beta.",
    customerBlurb: "Kontrollierte A/B-Tests für Kampagnenänderungen sind jetzt nicht mehr nur für Search, sondern auch für Shopping-, Audience- und Performance-Max-Kampagnen möglich. Damit lassen sich Änderungen an euren Kampagnen vor dem vollen Rollout statistisch absichern.",
    keyFactsDE: [
      "Neu: Unterstützung für Shopping-, Audience- und Performance-Max-Kampagnen zusätzlich zu Search.",
      "Neue Ergebnisseite mit Liniendiagramm (Treatment vs. Control) und Kampagnendetails.",
      "Closed Beta, global außer China, nur Englisch, Online-Oberfläche und API.",
      "Ablauf: 2–4 Wochen A/A-Baseline, dann mind. 2 (idealerweise 4) Wochen A/B-Test, max. 6 Monate Gesamtdauer.",
      "Ergebnisse mit 95 %-Konfidenzintervall; Kampagnen mit Shared-/Lifetime-Budgets nicht unterstützt.",
    ],
    emailHookDE: "Kunden können ihre Bidding-, Creative- oder Targeting-Änderungen jetzt auch in Shopping-, Audience- und Performance-Max-Kampagnen per kontrolliertem A/B-Test mit statistischer Absicherung prüfen, bevor sie live geschaltet werden.",
    pageCount: 18,
  },
  {
    id: "pmax-for-holiday-2025",
    file: "Performance Max for holiday 2025.pdf",
    title: "Performance Max für die Feiertagssaison: Taktischer Optimierungsfahrplan (August 2025)",
    // Die Präsentation selbst ist auf der Titelfolie mit "August 2025" datiert
    // (siehe summaryDE). Auf ausdrücklichen Wunsch von Angelika (11.08.2026)
    // wird hier abweichend vom Dokumentdatum das Anzeige-/Sortierdatum auf den
    // Upload-Tag gesetzt, damit der neu hochgeladene Eintrag ganz oben in der
    // Liste erscheint — keine Aussage über das tatsächliche Präsentationsdatum.
    date: "2026-08-11", dateKnown: true,
    docType: "Feature-Guide",
    summaryDE: "Taktischer Monat-für-Monat-Fahrplan (August bis Dezember) für die Optimierung von Performance-Max-Kampagnen im Einzelhandel während der Feiertagssaison, laut Titelfolie datiert auf August 2025 und damit ursprünglich für die Feiertagssaison 2025 verfasst. Themen: PMax-Grundlagen inkl. Copilot-Placements, Best Practices für kurzfristige Promotions, Checklisten für Asset-Gruppen/Budget/Suchthemen/Audience-Signale, Feed-Audit, Seasonality Adjustments, Conversion Value Rules, Data Exclusions sowie ein Beta-Feature-Fahrplan (Stand August 2025).",
    customerBlurb: "Dieser Leitfaden von Microsoft bündelt konkrete monatliche To-dos zur Optimierung von Performance-Max-Kampagnen für die Feiertagssaison — von Feed-Pflege im August bis zu Budget-/Zielanpassungen im Dezember. Das Dokument stammt aus August 2025; viele der beschriebenen Best Practices (Seasonality Adjustments, Search Themes, Feed-Checkliste) gelten weiterhin als generelle PMax-Vorgehensweise, konkrete Beta-Termine sollten aber gegengecheckt werden.",
    keyFactsDE: [
      "PMax-Anzeigen in Copilot erzielen laut Microsoft-1P-Daten (Feb.–Mai 2025) deutlich höhere Klickraten als in Search: +103 % bei Responsive Search Ads, +267 % bei Shopping Ads, +32 % bei Multimedia Ads; die Conversion-Rate liegt in Copilot um 14 % höher (5 % vs. 4,4 %).",
      "Laut einer Stichprobe von rund 500.000 Nutzerpfaden aus der Vorsaison stammen 65 % der November- und 44 % der Dezember-Conversions aus Klicks, die bereits im Oktober erfolgten.",
      "Empfohlener Monatsfahrplan: August/September für neue Launches, Restrukturierungen und Feed-Optimierung; Oktober für saisonales Messaging und Suchthemen; November/Dezember für Asset-Refresh, Seasonality Adjustments und Conversion Value Rules.",
      "Feeds haben laut Dokument eine 72-Stunden-Rampe, neue Assets bis zu 1 Tag; für die redaktionelle Freigabe sollten neue Creatives mindestens 48 Stunden vorher hochgeladen werden.",
      "Beta-Fahrplan (Stand August 2025) nennt u. a. 'New customer acquisition goal' im Pilot seit Juli 2025, Share-of-Voice-Metriken für November 2025 sowie Experiments/Incrementality-Testing als Pilot für Q1 2026 — diese Termine sollten mit dem aktuellen Stand gegengecheckt werden.",
    ],
    emailHookDE: null,
    pageCount: 49,
  },
  {
    id: "pmax-checklist",
    file: "PMAX Checklist.pdf",
    title: "Checkliste zur Optimierung von Performance-Max-Kampagnen",
    date: "2026-02-20", dateKnown: false,
    docType: "Feature-Guide",
    summaryDE: "Einseitige Checkliste mit zehn Handlungsfeldern für erfolgreiche Performance-Max-Kampagnen: Budget, Kampagnenstruktur, Signale, Feed-Optimierung, Gebotsstrategien, Monitoring, Reichweite, Zielgruppen-Targeting, Compliance und Partner-Ressourcen, ergänzt um drei Pro-Tipps.",
    customerBlurb: "Microsoft hat eine kompakte Checkliste veröffentlicht, mit der sich Performance-Max-Kampagnen entlang zehn zentraler Punkte optimieren lassen — von Budget über Signale bis Zielgruppen-Targeting. Wir gehen die gerne einmal gemeinsam für eure Kampagnen durch.",
    keyFactsDE: [
      "Empfiehlt Ziel-Targets statt reiner Budgetdeckel sowie den Budget-Schätzer.",
      "Rät zu separaten Kampagnen nach Land/Sprache/Budget/ROAS-Ziel und eigenen Asset-Gruppen für Promotions (Assets mind. 1 Tag vor Start hochladen).",
      "Empfiehlt möglichst viele Signale: Audience Signals, Search Themes, Mikro-Conversions, häufiger Offline-Conversion-Import.",
      "Smart Bidding: Zieländerungen in ca. 15 %-Schritten, Saisonalitäts-Anpassungen für Events wie Cyber Weekend.",
      "Pro-Tipps: ~2 Wochen Lernphase einplanen, auf neue Features achten, Feedback über Partner-Kanäle einreichen.",
    ],
    emailHookDE: null,
    pageCount: 1,
  },
  {
    id: "home-services-scale",
    file: "Ready, set, scale_Home services demand is heating up (Presentation) (1).pdf",
    title: "Ready, Set, Scale: Boomende Nachfrage im Bereich Home Services",
    date: "2026-03-18", dateKnown: true,
    docType: "Strategie-Trend",
    summaryDE: "Präsentation zur B2C-Vertikale 'Home Services' (Heizung/Klima, Klempner, Elektriker u. a.): saisonaler Nachfrageanstieg (Höhepunkt Frühsommer), typische Customer Journey am Beispiel HVAC, Einfluss generativer KI/Copilot auf das Suchverhalten, sowie Handlungsempfehlungen (Performance Max, Broad Match, In-Market Audiences, Audience Ads).",
    customerBlurb: "Microsoft zeigt in einer aktuellen Analyse, wie stark die Nachfrage im Bereich Home Services saisonal schwankt und welche Kampagnenstruktur sich dafür bewährt hat. Falls das zu eurer Branche passt, sprechen wir gerne über passendes Kampagnen-Timing.",
    keyFactsDE: [
      "US-Markt Home Services 2021 auf 370,86 Mrd. USD geschätzt, CAGR 19 % bis 2030 prognostiziert (Quelle: Gitnux, Dez. 2025).",
      "Microsoft-B2C-Werbeausgaben im Segment: +12 % CAGR seit 2023; Klicks +55 %, CTR +64 %, CPC -18 % (Okt. 2023–Dez. 2025).",
      "Text- + Audience-Ads-Kombination erzielt 3,5x mehr Klicks und 3,8x höhere Conversion-Rate als Text-Ads allein.",
      "Nach Performance-Max-Einführung: CTR im Schnitt +21 %, CPC -40 % (Vergleich 20 Wochen vor/nach).",
      "HVAC-Kaufentscheidung dauert im Schnitt 43 Tage, 35 Suchanfragen; empfohlenes Timing Mitte April bis Juni/Juli.",
    ],
    emailHookDE: null,
    pageCount: 56,
  },
  {
    id: "ki-kennzeichnungspflichten",
    file: "Rechtsanwalt Niklas Plutte - Webinar KI-Kennzeichnungspflichten.pdf",
    title: "KI-Kennzeichnungspflichten nach der EU-KI-Verordnung: Webinar mit Rechtsanwalt Niklas Plutte",
    date: "2026-08-02", dateKnown: false,
    docType: "Rechtliches",
    summaryDE: "Rechtsanwalt Niklas Plutte erläutert die Kennzeichnungspflichten für KI-generierte Inhalte nach Art. 50 der EU-KI-Verordnung (AI Act), gültig ab 2. August 2026 (Maschinenlesbarkeits-Pflicht erst ab 2. Dezember 2026). Fünf Einzelpflichten, zugeordnet zu den Rollen 'Anbieter' und 'Betreiber', inkl. Deepfake- und Text-Kennzeichnung sowie Bußgeldrisiken.",
    customerBlurb: "Ab dem 2. August 2026 gelten neue Kennzeichnungspflichten für KI-generierte Inhalte nach der EU-KI-Verordnung — relevant, falls ihr KI-generierte Texte oder Bilder in eurer Werbung einsetzt. Wir informieren euch gerne genauer, was das für eure Kampagnen bedeutet.",
    keyFactsDE: [
      "Fünf Kennzeichnungspflichten nach Art. 50 AI Act: direkte KI-Interaktion, Maschinenlesbarkeit, Emotionserkennung/Biometrie, Deepfakes, KI-generierte Texte.",
      "Gültig ab 2. August 2026 für Unternehmen/Selbstständige/berufliche Nutzer — nicht für Privatpersonen.",
      "Deepfake-Definition (Art. 3 Nr. 60): KI-erzeugter Inhalt, der echt wirken könnte; reine Bearbeitungshilfen zählen laut Referent nicht dazu.",
      "KI-generierte Texte nur kennzeichnungspflichtig bei öffentlichem Interesse UND ohne redaktionelle Prüfung.",
      "Bußgelder bis 15 Mio. € oder 3 % des weltweiten Konzernjahresumsatzes (Art. 99 Abs. 4 g AI Act); zusätzlich drohen bei Deepfakes Persönlichkeitsrechts-Ansprüche.",
    ],
    emailHookDE: null,
    pageCount: 39,
  },
  {
    id: "future-of-shopping-retail",
    file: "The Future of Shopping Retail_SoWeSpoke.pdf",
    title: "Die Zukunft des Shoppings im Einzelhandel: Der agentische Wandel im E-Commerce",
    date: "2026-08-02", dateKnown: false,
    docType: "Strategie-Trend",
    summaryDE: "Beschreibt, wie agentenbasierte KI (v. a. Microsoft Copilot) die Customer Journey im E-Commerce verändert. Drei Handlungsfelder: Sichtbarkeit in KI-Suchergebnissen (GEO/AEO), eigene 'Brand Agents' für Kund:innen-Konversationen, und Checkout direkt in Copilot. Jüngste zitierte Quelle: November 2025.",
    customerBlurb: "Microsoft beschreibt, wie sich der Einkauf durch KI-Assistenten wie Copilot verändert — inklusive der Möglichkeit, direkt im Gespräch zu kaufen (Copilot Checkout). Für den Einzelhandel könnte das mittelfristig ein neuer, relevanter Vertriebsweg werden.",
    keyFactsDE: [
      "Werbeausgaben für KI-Suche sollen schneller wachsen als frühere Wellen: 25,93 Mrd. USD im 4. Jahr vs. 18,59 Mrd. USD bei Retail Media (eMarketer, Juli 2025).",
      "800 % Anstieg (YoY) beim KI-gesteuerten Traffic zu Händler-Websites (Reuters, Black-Friday-Bezug).",
      "72 % der Konsument:innen erwarten binnen 12 Monaten agentenbasierte KI-Einkaufserlebnisse; Journeys 33 % kürzer (Microsoft Research, Sept. 2025).",
      "'Brand Agents' sollen laut internen Daten zu 3x höherer Conversion-Rate in begleiteten Sitzungen führen.",
      "Copilot Checkout basiert auf Stripe/Shopify/PayPal und UCP/ACP; Käufe steigen nach Copilot-Interaktion um 53 %, bei klarer Kaufabsicht um 194 % (Microsoft-Daten, Dez. 2024).",
    ],
    emailHookDE: "Mit den neuen Copilot-Checkout- und Brand-Agent-Funktionen von Microsoft können Kund:innen künftig direkt im Copilot-Chat beraten werden und dort auch einkaufen, ohne die Unterhaltung zu verlassen.",
    pageCount: 32,
  },
  {
    id: "valentines-day-2026",
    file: "Valentines_Day_GNO_-_US_-_Feb2026.pdf",
    title: "Valentinstag 2026 (USA): Saisonale Kampagnenstrategie und Shopper-Insights",
    date: "2026-02-01", dateKnown: true,
    docType: "Saisonal",
    summaryDE: "Saisonale Kampagnenempfehlungen für den Valentinstag 2026 in den USA: Suchinteresse-Verlauf ab Mitte Dezember, Klick-/CPC-Prognose, relevante Suchthemen und drei Shopper-Personas (Thoughtful Romantic, Last-Minute Scrambler, Self Gifter) mit passenden Werbeempfehlungen.",
    customerBlurb: "Microsoft hat aktuelle Shopper-Insights zum Valentinstag 2026 veröffentlicht, inklusive typischer Suchmuster und Timing-Empfehlungen für Kampagnen. Falls Valentinstag für eure Produkte relevant ist, planen wir das Timing gerne gemeinsam.",
    keyFactsDE: [
      "Prognose Jan/Feb 2026: +4 % Klicks, -1 % CPC gegenüber Vorjahr (Microsoft Internal).",
      "Galentine's-Day-Suchen +13 % YoY, Kerzen-Suchen +9 % YoY.",
      "Laut Statista 2025: 50 % achten auf günstigere Geschenke, 48 % auf Rabatte/Coupons; 2 % feiern wegen höherer Preise gar nicht.",
      "59–69 % starten die Suche non-brand, konvertieren aber häufig auf Brand; 61 % mit nur einem Touchpoint konvertieren direkt auf Brand.",
      "Drei Personas mit unterschiedlichem Kaufverhalten und Timing; empfohlene Kampagnenlaufzeit Mitte Dezember bis Anfang Februar.",
    ],
    emailHookDE: null,
    pageCount: 17,
  },
  {
    id: "winning-holiday-moments",
    file: "Winning holiday moments_Practical strategies for seasonal success (Presentation).pdf",
    title: "Erfolgreiche Feiertagsmomente: Praktische Strategien für die Saison",
    // Kein Datum im Dokument selbst (mehrfach geprüft: Titelfolie, Fußzeilen,
    // Referentin-Folie) — Juli 2026 nach Angelikas Bestätigung gesetzt.
    date: "2026-07-01", dateKnown: true,
    docType: "Saisonal",
    summaryDE: "Praktische Strategien für die Feiertagssaison in vier Phasen: 'Wrap the Basics' (Juli/Aug.), 'Gift Them a Reason' (Sept./Okt.), 'Ring in the Sales' (Nov./Dez.) und 'Unbox What's Next' (Dez./Jan.). Konkrete Empfehlungen zu Kampagnenstruktur, Produkt-Feeds/UCP, saisonalen Zielgruppen und Bidding, mit zwei Kundenfallstudien.",
    customerBlurb: "Microsoft hat praktische Strategien für die Feiertagssaison veröffentlicht, aufgeteilt in vier Phasen von der Vorbereitung im Sommer bis zur Auswertung im Januar. Wir schauen gerne gemeinsam, welche Phase für eure Kampagnenplanung als Nächstes ansteht.",
    keyFactsDE: [
      "74 % der US-Shopper recherchieren 2026 vor Black Friday/Cyber Monday im Voraus (2025: 69 %).",
      "63 % beginnen Feiertags-Einkäufe vor Halloween; 37 % vor dem Amazon Prime Day im Oktober.",
      "Durchschnittliche Conversion-Journey: 52 Tage; Cyber-5 erzeugt 9 % der Feiertags-Conversions bei nur 7 % der Klicks.",
      "Oktober-Klicks sind Ursprung von 56 % der November- und 35 % der Dezember-Conversions.",
      "Fallstudie JD Sports: +747 % Klicks, 99 % Brand-Core-Conversion-Rate. Fallstudie LOOKFANTASTIC: 2,7x Conversion-Steigerung durch Audience Ads.",
    ],
    emailHookDE: null,
    pageCount: 61,
  },
  {
    id: "winning-holiday-moments-uk-2026",
    file: "Winning holiday moments that matter most_July 16 2026.pdf",
    title: "Winning Holiday Moments That Matter Most: UK-Feiertagsforschung 2026",
    date: "2026-07-16", dateKnown: true,
    docType: "Saisonal",
    summaryDE: "Aktuelle Empfehlungen aus dem Microsoft-Webinar für die Planung des Weihnachtsgeschäfts 2026: früher Start, klare Preis-/Mehrwert-Kommunikation, passender Kanal-Einsatz je Phase (Audience Ads → Performance Max → Search/Shopping → Remarketing) sowie KI-Sichtbarkeit (GEO, IndexNow, UCP/Copilot Checkout).",
    customerBlurb: "Aus dem aktuellen Microsoft-Webinar „Winning Holiday Moments That Matter Most“ — die wichtigsten Empfehlungen für die Planung des Weihnachtsgeschäfts 2026:\n\n• Frühzeitig starten: Die Nachfrage steigt bereits ab Oktober, während die Klickpreise dann noch vergleichsweise niedrig sind — auch die Markenentscheidung fällt oft schon früh.\n• Preis und Mehrwert klar kommunizieren: Viele achten verstärkt auf Preise und Rabatte — Vorteile wie Preis, Qualität und Versand sollten in Anzeigen deutlich hervorgehoben werden.\n• Kampagnenarten passend einsetzen: Audience Ads (Oktober, frühe Nachfrage) → Performance Max (November, Hauptphase) → Search/Shopping (November–Dezember, Kaufabsicht) → Remarketing (Dezember–Januar, Spätkäufer).\n• KI verändert die Produktsuche: Neben klassischer Suche gewinnen KI-Antworten und Einkaufsassistenten an Bedeutung — Websites sollten für beide gut lesbar sein.\n• IndexNow kann Suchmaschinen automatisch über neue/aktualisierte Inhalte informieren, z. B. neue Produkte oder Aktionsseiten.\n\nMicrosoft erwartet für den Einzelhandel in sechs europäischen Märkten mehr Klicks bei niedrigeren Klickpreisen — eine frühzeitige Vorbereitung könnte sich lohnen.",
    keyFactsDE: [
      "Nachfrage steigt bereits ab Oktober bei noch vergleichsweise niedrigen Klickpreisen — auch die Markenentscheidung fällt oft früh in der Kaufphase.",
      "Aktivierung nach Phase: Oktober → Audience Ads (frühe Nachfrage) · November → Performance Max (Hauptphase) · Nov.–Dez. → Search/Shopping (Kaufabsicht) · Dez.–Jan. → Remarketing (Spätkäufer).",
      "EU6-Prognose Okt.–Dez. 2026 (Retail): +13 % Klicks, −4,5 % CPC ggü. Vorjahr.",
      "KI-Antworten und Einkaufsassistenten gewinnen neben klassischer Suche an Bedeutung — Relevanz für Such- UND KI-Systeme wichtig (GEO).",
      "UCP (Universal Commerce Protocol) in Microsoft Merchant Center ermöglicht Copilot Checkout direkt im Gespräch, inkl. aktueller Produktdaten und Rückgabebedingungen.",
    ],
    emailHookDE: "Mit Copilot Checkout und dem Universal Commerce Protocol (UCP) können eure Kund:innen künftig direkt im Copilot-Gespräch einkaufen — inklusive aktueller Produktdaten, Rückgabebedingungen und Rabatten, ohne die Unterhaltung zu verlassen.",
    pageCount: 67,
  },
];
