/**
 * Tickets — reine Beispieldaten (kein Zoho-Desk-API-Zugriff, siehe
 * DESIGN-MASTERPROMPT.md Abschnitt 8 "Einordnung": Zoho Desk erfordert
 * OAuth-Client + Org-ID, die aktuell nicht vorliegen). Feldnamen bewusst
 * nah an einer echten Zoho-Desk-Ticket-Antwort (subject, status, priority,
 * dueDate, contactName, assigneeInitials), damit ein späterer Umstieg auf
 * echte Daten ohne UI-Umbau möglich ist — nur diese Datei würde ersetzt.
 * Alle Einträge tragen isPlaceholder: true (etabliertes Muster aus
 * case-studies-data.js) statt echte Daten optisch vorzutäuschen.
 *
 * status: "open" | "pending" | "completed" | "cancelled"
 * priority: "high" | "medium" | "low"
 */
const TICKETS_DATA = [
  {
    id: "SPK-1042",
    subject: "Conversion-Tracking zeigt seit Update keine Käufe mehr",
    contactName: "Julia Nicola",
    accountName: "OMR Digital GmbH",
    assigneeInitials: "MK",
    assigneeName: "M. Kessler",
    status: "open",
    priority: "high",
    category: "Tracking",
    dueDate: "2026-08-14",
    createdDate: "2026-08-10",
    isPlaceholder: true,
  },
  {
    id: "SPK-1041",
    subject: "Neues Werbekonto für Kunde einrichten (MCC-Verknüpfung)",
    contactName: "Jack Ohlsen",
    accountName: "Nordlicht Möbel",
    assigneeInitials: "AS",
    assigneeName: "A. Sliwak",
    status: "pending",
    priority: "medium",
    category: "Kontoeinrichtung",
    dueDate: "2026-08-13",
    createdDate: "2026-08-09",
    isPlaceholder: true,
  },
  {
    id: "SPK-1040",
    subject: "Performance-Max-Kampagne läuft aus dem Budget",
    contactName: "Angela Carol",
    accountName: "Bloom Kosmetik",
    assigneeInitials: "TR",
    assigneeName: "T. Reinke",
    status: "completed",
    priority: "high",
    category: "Kampagnen-Optimierung",
    dueDate: "2026-08-05",
    createdDate: "2026-08-01",
    isPlaceholder: true,
  },
  {
    id: "SPK-1039",
    subject: "Rechnung Juli doppelt gestellt",
    contactName: "Christopher JD",
    accountName: "Nordlicht Möbel",
    assigneeInitials: "PL",
    assigneeName: "P. Lang",
    status: "cancelled",
    priority: "low",
    category: "Abrechnung",
    dueDate: "2026-08-02",
    createdDate: "2026-07-30",
    isPlaceholder: true,
  },
  {
    id: "SPK-1038",
    subject: "Zugriff für neuen Teamkollegen auf Werbekonto freigeben",
    contactName: "Zoe Ahrens",
    accountName: "Bloom Kosmetik",
    assigneeInitials: "AS",
    assigneeName: "A. Sliwak",
    status: "completed",
    priority: "medium",
    category: "Zugriffsrechte",
    dueDate: "2026-08-06",
    createdDate: "2026-08-04",
    isPlaceholder: true,
  },
  {
    id: "SPK-1037",
    subject: "Monatsreport lässt sich nicht als PDF exportieren",
    contactName: "Vanessa Sander",
    accountName: "OMR Digital GmbH",
    assigneeInitials: "MK",
    assigneeName: "M. Kessler",
    status: "open",
    priority: "low",
    category: "Reporting",
    dueDate: "2026-08-15",
    createdDate: "2026-08-11",
    isPlaceholder: true,
  },
  {
    id: "SPK-1036",
    subject: "Keyword-Vorschläge für neue Winter-Kampagne",
    contactName: "Alexander Busch",
    accountName: "Nordlicht Möbel",
    assigneeInitials: "TR",
    assigneeName: "T. Reinke",
    status: "pending",
    priority: "medium",
    category: "Kampagnen-Optimierung",
    dueDate: "2026-08-18",
    createdDate: "2026-08-08",
    isPlaceholder: true,
  },
  {
    id: "SPK-1035",
    subject: "Rechtliche Prüfung: neue Anzeigentexte für Gesundheitsprodukt",
    contactName: "Angela Carol",
    accountName: "Bloom Kosmetik",
    assigneeInitials: "PL",
    assigneeName: "P. Lang",
    status: "open",
    priority: "high",
    category: "Sonstiges",
    dueDate: "2026-08-13",
    createdDate: "2026-08-10",
    isPlaceholder: true,
  },
  {
    id: "SPK-1034",
    subject: "SAP-ID für neues Verwaltungskonto beantragen",
    contactName: "Jack Ohlsen",
    accountName: "Nordlicht Möbel",
    assigneeInitials: "AS",
    assigneeName: "A. Sliwak",
    status: "completed",
    priority: "low",
    category: "Kontoeinrichtung",
    dueDate: "2026-07-29",
    createdDate: "2026-07-25",
    isPlaceholder: true,
  },
  {
    id: "SPK-1033",
    subject: "Conversion-Werte stimmen nicht mit Shopify überein",
    contactName: "Julia Nicola",
    accountName: "OMR Digital GmbH",
    assigneeInitials: "MK",
    assigneeName: "M. Kessler",
    status: "pending",
    priority: "high",
    category: "Tracking",
    dueDate: "2026-08-16",
    createdDate: "2026-08-11",
    isPlaceholder: true,
  },
  {
    id: "SPK-1032",
    subject: "Frage zur Abrechnung von Managementgebühren",
    contactName: "Christopher JD",
    accountName: "Bloom Kosmetik",
    assigneeInitials: "PL",
    assigneeName: "P. Lang",
    status: "completed",
    priority: "medium",
    category: "Abrechnung",
    dueDate: "2026-08-01",
    createdDate: "2026-07-28",
    isPlaceholder: true,
  },
  {
    id: "SPK-1031",
    subject: "Zugriff für ausgeschiedenen Mitarbeiter entziehen",
    contactName: "Zoe Ahrens",
    accountName: "Nordlicht Möbel",
    assigneeInitials: "AS",
    assigneeName: "A. Sliwak",
    status: "cancelled",
    priority: "low",
    category: "Zugriffsrechte",
    dueDate: "2026-07-27",
    createdDate: "2026-07-26",
    isPlaceholder: true,
  },
];
